@keycloak_url=https://auth-dev.snowse.io
 
# double check cookies in settings for http requests
# rest client settings > uncheck remember cookies
 
 
###
# create challenge: echo -n "randomsecretstringrandomsecretstringrandomsecretstringrandomsecretstring" | sha256sum -b | xxd -p -r | base64 | tr '/+' '_-' | tr -d '='
# code_challenge: gR16hjqNRs3ofOuVtlHGwabDPymJQYT8sJ1UxnW09qk
# i think code_verifier has length requirements
# @name first
 
GET {{keycloak_url}}/realms/DevRealm/protocol/openid-connect/auth
    ?client_id=mateo-chat
    &redirect_uri=http://localhost:5173
    &response_type=code
    &response_mode=fragment
    &state=
    &code_challenge=gR16hjqNRs3ofOuVtlHGwabDPymJQYT8sJ1UxnW09qk
    &code_challenge_method=S256
    &scope=profile openid email
### get url from action of previous form
### & is going to be html escaped
# @name manualLogin
post https://auth-dev.snowse.io/realms/DevRealm/login-actions/authenticate?session_code=u7IGmhp8JDJpeHs3OHUJMfFhhkIlDWiKKkKeIxgSsmc&execution=4f8d2666-17f4-4c9c-8478-71b1c3086ad3&client_id=mateo-chat&tab_id=jlb1a-jX-KM&client_data=eyJydSI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTE3MyIsInJ0IjoiY29kZSIsInJtIjoiZnJhZ21lbnQiLCJzdCI6IiJ9
Content-Type: application/x-www-form-urlencoded
Cookie: {{first.response.headers.Set-Cookie}}
 
username=alex
&password=alex
 
### turn the code into a token
# @name getToken
post {{keycloak_url}}/realms/advanced-frontend/protocol/openid-connect/token
Cookie: {{first.response.headers.Set-Cookie}}
Content-Type: application/x-www-form-urlencoded
 
client_id=alex-in-class
&code=get from previous request
&redirect_uri=needs to match the first request
&code_verifier=needs to be the code used to generate the sha256 string
&grant_type=authorization_code
 
###
# https://auth.snowse.duckdns.org/realms/advanced-frontend/.well-known/openid-configuration
# for this to work, you must request the openid scope at the begining of the workflow
# @name useToken
 
get {{keycloak_url}}/realms/advanced-frontend/protocol/openid-connect/userinfo
Authorization: Bearer accessTokenGoesHere