@llm_api_base= https://ai-snow.reindeer-pinecone.ts.net/api/chat/completions

POST {{llm_api_base}}
Content-Type: application/json
Authorization: Bearer {{$dotenv API_KEY}}

{
    "model": "gpt-oss-120b",
    "messages": [
      {
        "role": "user",
        "content": "Why is the sky blue?"
      }
    ]
}

### Test local chat endpoint

POST http://localhost:4000/api/chat
Content-Type: application/json

{
    "message": "Hello! How are you doing today?"
}