apiVersion: apps/v1
kind: Deployment
metadata:
  name: mateo-ai-backend
  namespace: $NAMESPACE
  labels:
    app: aichat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aichat-backend
  template:
    metadata:
      labels:
        app: aichat-backend
    spec:
      containers:
      - name: mateo-ai-backend
        image: mateotomaszeuski/aichat-backend:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "postgres://appuser:apppassword@mateo-ai-database:5432/appdb"
        - name: API_KEY
          value: "sk-67019917671644c7a1612fa588ddaa6a"
        - name: OIDC_ISSUER
          value: "https://auth-dev.snowse.io/realms/DevRealm"
        - name: OIDC_JWKS_URI
          value: "https://auth-dev.snowse.io/realms/DevRealm/protocol/openid-connect/certs"